### ISSUE TITLE
Error: Cannot find module '/tmp/workspace/web-dynamify/variables/pages/forms/no_index.json'

### ISSUE THREAD

**Issue by jrichardsz** [rad-frameworks/web-dynamify#1]
When an html exist (no_index.html) withtout its json file, I get this error:

```
Error: Cannot find module '/tmp/workspace/web-dynamify/variables/pages/forms/no_index.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at /tmp/workspace/web-dynamify/server.js:38:40
    at Layer.handle [as handle_request] (/tmp/workspace/web-dynamify/node_modules/express/lib/router/layer.js:95:5)
    at next (/tmp/workspace/web-dynamify/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/tmp/workspace/web-dynamify/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/tmp/workspace/web-dynamify/node_modules/express/lib/router/layer.js:95:5)
    at /tmp/workspace/web-dynamify/node_modules/express/lib/router/index.js:281:22
```

**Comment by jrichardsz** [comment]
done with https://github.com/rad-frameworks/web-dynamify/pull/3
